export const FETCH_AUTOCOMPLETE_FULFILLED = 'FETCH_AUTOCOMPLETE_FULFILLED';
export const FETCH_AUTOCOMPLETE_NO_MATCH = 'FETCH_AUTOCOMPLETE_NO_MATCH';
export const FETCH_AUTOCOMPLETE_REJECTED = 'FETCH_AUTOCOMPLETE_REJECTED';
export const FETCH_AUTOCOMPLETE_TYPING = 'FETCH_AUTOCOMPLETE_TYPING';
export const FETCH_AUTOCOMPLETE = 'FETCH_AUTOCOMPLETE';
