USE winereview;
CREATE TABLE wine (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
year YEAR(4) NOT NULL,
name VARCHAR(100) NOT NULL,
country VARCHAR(50) NOT NULL,
color VARCHAR(15) NOT NULL,
producer VARCHAR(50) NOT NULL);

CREATE TABLE reviews (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
comment VARCHAR(50) NOT NULL,
score INT NOT NULL,
boughtfrom VARCHAR(50) NOT NULL,
price VARCHAR(10) NOT NULL,
reviewer VARCHAR(50) NOT NULL,
glass TINYINT(1) NOT NULL,
fk_wine_id INT NOT NULL,
added TIMESTAMP);

CREATE TABLE grapes (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
grape VARCHAR(100) NOT NULL,
fk_wine_id INT NOT NULL
);


ALTER TABLE grapes 
ADD CONSTRAINT FK_grape_wine_id 
FOREIGN KEY (fk_wine_id) REFERENCES wine(id) 
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE reviews 
ADD CONSTRAINT FK_review_wine_id 
FOREIGN KEY (fk_wine_id) REFERENCES wine(id) 
ON UPDATE CASCADE
ON DELETE CASCADE;

GRANT ALL PRIVILEGES ON `winereviews`.* TO 'wineuser'@'localhost'