export const FETCH_WINES_FULFILLED = 'FETCH_WINES_FULFILLED';
export const FETCH_WINES_REJECTED = 'FETCH_WINES_REJECTED';
export const FETCH_WINES_NO_MATCH = 'FETCH_WINES_NO_MATCH';
export const FETCH_WINES = 'FETCH_WINES';
export const REMOVE_FROM_CELLAR_FULFILLED = 'REMOVE_FROM_CELLAR_FULFILLED';
export const REMOVE_FROM_CELLAR_REJECTED = 'REMOVE_FROM_CELLAR_REJECTED';
export const REMOVE_FROM_CELLAR = 'REMOVE_FROM_CELLAR';
export const TOGGLE_DETAILED_WINE_RESULT_VIEW = 'TOGGLE_DETAILED_WINE_RESULT_VIEW';
