export const FETCH_REVIEWS_FULFILLED = 'FETCH_REVIEWS_FULFILLED';
export const FETCH_REVIEWS_REJECTED = 'FETCH_REVIEWS_REJECTED';
export const FETCH_REVIEWS_NO_MATCH = 'FETCH_REVIEWS_NO_MATCH';
export const FETCH_REVIEWS = 'FETCH_CLICKED_ITEM';
export const TOGGLE_DETAILED_REVIEW_RESULT_VIEW = 'TOGGLE_DETAILED_REVIEW_RESULT_VIEW';
